version: '3.8'

services:
  app:
    build: .
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  migrate:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ./migrate.sh

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'
volumes:
  db_data:
